db:
  path: ./assistance.sqlite3
  command: "SELECT * FROM assistance"

retriever:
  cls: chatbot.retrievers.TfIdf
  indexing_fn: "lambda df : df['title']"

model:
  cls: chatbot.models.HFQandA
  kwargs:
    model_path: "etalab-ia/camembert-base-squadFR-fquad-piaf"

wrappers:
  - - chatbot.wrappers.AppendURLWrapper
    - []
    - {}

  - - chatbot.wrappers.MinimumCertaintyWrapper
    - [0.05]
    - {}

  - - chatbot.wrappers.AbsoluteAnswerWrapper
    - []
    - {}
